### ISSUE TITLE
tsc cannot find declaration module for request after upgrading from 6.4.0 to 6.5.0

### ISSUE THREAD

**Issue by hlian** [sendgrid/sendgrid-nodejs#1027]
#### Issue Summary

After dependabot upgraded our library to v6.5.0 from v6.4.0, we ran into this error on CI:

```
../../node_modules/@sendgrid/client/src/request.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'request'. '/home/circleci/project/node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm install @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

1 import {OptionsWithUrl} from "request";
                               ~~~~~~~~~
```

It appears to be a missing dependency. `@types/request` is marked as a devDependency, but the `.d.ts` makes it a non-dev dependency, if that makes sense.

#### Technical details:

* sendgrid-nodejs Version: 6.5.0
* Node.js Version: 12.14.0

**Comment by childish-sambino** [comment]
It was moved to a devDependency here: https://github.com/sendgrid/sendgrid-nodejs/pull/908

@SPARTAN563 Thoughts on this? A request lib type is being exposed here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/request.d.ts

My understanding is it needs to be a dependency and not devDependency: https://stackoverflow.com/a/46011417

**Comment by lirbank** [comment]
Published packages should include types they rely on in `dependencies`, not `devDependencies`, see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

**Comment by garybernhardt** [comment]
I opened #906, which prompted the original move of @types packages to devDependencies. @lirbank's link makes it very clear that that was a mistake. Sorry about that!

**Comment by SPARTAN563** [comment]
Thanks for sorting this out folks, I've approved #1035 so now it's just a matter of waiting on the SendGrid devs to get it merged and released :+1:.

**Comment by childish-sambino** [comment]
Approved and merged. Next release is slated for 2020-02-05 (roughly every 2 weeks going forward).
