### PR TITLE
fix #1027: Move @types/request back to dependencies

### LINKED ISSUE #1027: tsc cannot find declaration module for request after upgrading from 6.4.0 to 6.5.0
#### Issue Summary

After dependabot upgraded our library to v6.5.0 from v6.4.0, we ran into this error on CI:

```
../../node_modules/@sendgrid/client/src/request.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'request'. '/home/circleci/project/node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm install @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

1 import {OptionsWithUrl} from "request";
                               ~~~~~~~~~
```

It appears to be a missing dependency. `@types/request` is marked as a devDependency, but the `.d.ts` makes it a non-dev dependency, if that makes sense.

#### Technical details:

* sendgrid-nodejs Version: 6.5.0
* Node.js Version: 12.14.0

### PR DESCRIPTION
**Pull request by hlian**
Fixes #1027. 

This moves the `@types/request` dependency back into the non-dev category, unbreaking the package for TypeScript users. This is described as best practice here:

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

I also bumped the version up from 2.0.4, which was [two years old](https://www.npmjs.com/package/@types/request), to 2.48.4. I am unsure how DefinitelyTyped versions their types packages... but request v2.88.0 is the most recent version on NPM, so I assume y'all want the latest @types/request version also.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @hlian,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX
